name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run : echo "Staring the first job"
      - name: Multi-Line run-shell-commands
        run: |
          node -v
          npm -v
          mkdir Hello
  parallel-job:
    runs-on: macos-latest
    steps:
     -  name: Check SW version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      -   name: echo a string
          run: Write-Output " Windows String"
      -   name: Error Step
          run: doesnotexits