name: Simple Actions
on: [push]

jobs:
    Get-repository:
        runs-on: ubuntu-latest
        steps:
         - name: Check-available-files
           run: |
             pwd
             ls -lrtia
         - name: Create-local-repository
           run: |
             git init
             git remote add origin https://github.com/Dennis-kiki/company-website.git
             git fetch
             git checkout main
         - name: Check-local-repository
           run: ls -lrtia

    Simple-Action:
        runs-on: ubuntu-latest
        steps:
          - name: Simple JS action
            id: greet
            uses: actions/hello-world-javascript-action@344c7223fc4636280d179071c62268c95e0a17bd
            with:
              who-to-greet: Shikurus

          - name: Log greeting Time
            run: echo "${{steps.greet.outputs.time}}"
            
