name: Repository-events
on: [push, pull_request, issues]

jobs:
 checkout:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo $GITHUB_SHA
        echo $GITHUB_REF
     - uses: actions/checkout@v3
 Check-check:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
        - name: Files after
          run: ls -lrta
    