name: Second Workflow
on: [push]
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Install npm
             run: sudo apt install npm

           - name: Install docker
             run: sudo install docker.io

           - name: Check npm version
             run: |
                 npm -v
                 echo " npm version checked!"
                 node -v
                 docker --version
