name: Second Workflow
on: [push]
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Install npm
             run: sudo apt install npm

           - name: Install apache2
             run: sudo apt install apache2

           - name: install php
             run: sudo apt install php

    Check_dependancies:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
         - name: Check dependancies version
           run: |
                 npm -v
                 echo "$(npv -v)"
                 node -v
                 apache2 -v
    
    Passing_error_message:
        runs-on: ubuntu-latest
        needs: [Check_dependancies]
        steps:
         - name: Display Error Message
           run: echo "::error::No variable identified"
