name: Second Workflow
on: [push]
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Install npm
             run: sudo apt install npm

           - name: Install apache2
             run: sudo apt install apache2

           - name: install php
             run: sudo apt install php

    Check_dependancies:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
         - name: Check npm version
           run: |
                 npm -v
                 echo " npm version checked!"
                 node -v
                 apache2 -v
