name: Second Workflow
on: [push]
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Install npm
             run: echo " Install npm!"

           - name: Check npm version
             run: |
                 npm -v
                 echo " npm version checked!"
                 node -v
