name: Third Workflow
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Shell variables
              run: |
                 pwd
                 mkdir Hello
                 ls -larti
                 echo "Done!"
    Step_two:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: More-shell-cmd
              run:
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
